repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: "^(venv|__jac_gen__)/"

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: "^(venv|__jac_gen__)/"
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        additional_dependencies:
          - pep8-naming
          - flake8_docstrings
          - flake8_comprehensions
          - flake8_bugbear
          - flake8_annotations
          - flake8_simplify
        exclude: "^(venv|__jac_gen__)/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: "^(venv|__jac_gen__)/"
        args:
          - --follow-imports=silent
          - --ignore-missing-imports
          - --explicit-package-bases
        additional_dependencies:
          - types-PyYAML
          - types-requests

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        args: ['scan', '.']
        files: \.(py|jac|txt|yaml|json)$  # Extend this regex if needed
        exclude: "^(venv|__jac_gen__|.mypy_cache|.jac_mypy_cache)/"